version: '3.9'

services:
  panel-database:
    image: postgres:14-alpine
    ports:
     - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Mam@d123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=panel
  panel-webserver:
    build: "./Panel"
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=panel-database
      - POSTGRES_PASSWORD=Mam@d123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=panel
    depends_on:
      - panel-database
  ad-server-webserver:
    build: "./AdServer"
    ports:
      - 9000:9000
    depends_on:
      - panel-webserver
  event-server-webserver:
    build: "./EventServer"
    ports:
      - 9002:7000
    depends_on:
      - panel-webserver
  publisher-site-webserver:
    build: "./PublisherWebsite"
    ports:
      - 80:9001
    depends_on:
      - panel-webserver

volumes:
  pgdata: